import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
  className="min-h-screen"
  style={{
    backgroundImage: "url('/wallpaper.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
  }}
>

        <div className="absolute inset-0 bg-blue-900/50 z-0" />
        <div className="relative z-10 flex justify-center items-center min-h-screen p-4">
          {children}
        </div>
      </body>
    </html>
  )
}
